var SPORTS = {
  NBA: [
    { id: 1, name: "Atlanta Hawks", pref: "nba-atl" },
    { id: 2, name: "Boston Celtics", pref: "nba-nos" },
    { id: 17, name: "Brooklyn Nets", pref: "nba-bkn" },
    { id: 30, name: "Charlotte Hornets", pref: "nba-cha" },
    { id: 4, name: "Chicago Bulls", pref: "nba-chi" },
    { id: 5, name: "Cleveland Cavaliers", pref: "nba-cle" },
    { id: 6, name: "Dallas Mavericks", pref: "nba-dal" },
    { id: 7, name: "Denver Nuggets", pref: "nba-den" },
    { id: 8, name: "Detroit Pistons", pref: "nba-det" },
    { id: 9, name: "Golden State Warriors", pref: "nba-gs" },
    { id: 10, name: "Houston Rockets", pref: "nba-hou" },
    { id: 11, name: "Indiana Pacers", pref: "nba-ind" },
    { id: 12, name: "LA Clippers", pref: "nba-lac" },
    { id: 13, name: "Los Angeles Lakers", pref: "nba-lal" },
    { id: 29, name: "Memphis Grizzlies", pref: "nba-mem" },
    { id: 14, name: "Miami Heat", pref: "nba-mia" },
    { id: 15, name: "Milwaukee Bucks", pref: "nba-mil" },
    { id: 16, name: "Minnesota Timberwolves", pref: "nba-min" },
    { id: 3, name: "New Orleans Pelicans", pref: "nba-no" },
    { id: 18, name: "New York Knicks", pref: "nba-ny" },
    { id: 25, name: "Oklahoma City Thunder", pref: "nba-okc" },
    { id: 19, name: "Orlando Magic", pref: "nba-orl" },
    { id: 20, name: "Philadelphia 76ers", pref: "nba-phi" },
    { id: 21, name: "Phoenix Suns", pref: "nba-phx" },
    { id: 22, name: "Portland Trail Blazers", pref: "nba-por" },
    { id: 23, name: "Sacramento Kings", pref: "nba-sac" },
    { id: 24, name: "San Antonio Spurs", pref: "nba-sa" },
    { id: 25, name: "Toronto Raptors", pref: "nba-tor" },
    { id: 26, name: "Utah Jazz", pref: "nba-utah" },
    { id: 27, name: "Washington Wizards", pref: "nba-wsh" },
  ],
  NFL: [
    { id: 22, name: "Arizona Cardinals", pref: "nfl-ari" },
    { id: 1, name: "Atlanta Falcons", pref: "nfl-atl" },
    { id: 33, name: "Baltimore Ravens", pref: "nfl-bal" },
    { id: 2, name: "Buffalo Bills", pref: "nfl-buf" },
    { id: 29, name: "Carolina Panthers", pref: "nfl-car" },
    { id: 3, name: "Chicago Bears", pref: "nfl-chi" },
    { id: 4, name: "Cincinnati Bengals", pref: "nfl-cin" },
    { id: 5, name: "Cleveland Browns", pref: "nfl-cli" },
    { id: 6, name: "Dallas Cowboys", pref: "nfl-dal" },
    { id: 7, name: "Denver Broncos", pref: "nfl-den" },
    { id: 8, name: "Detroit Lions", pref: "nfl-det" },
    { id: 9, name: "Green Bay Packers", pref: "nfl-gb" },
    { id: 34, name: "Houston Texans", pref: "nfl-hou" },
    { id: 11, name: "Indianapolis Colts", pref: "nfl-ind" },
    { id: 30, name: "Jacksonville Jaguars", pref: "nfl-jax" },
    { id: 12, name: "Kansas City Chiefs", pref: "nfl-kc" },
    { id: 13, name: "Las Vegas Raiders", pref: "nfl-lv" },
    { id: 24, name: "Los Angeles Chargers", pref: "nfl-lac" },
    { id: 14, name: "Los Angeles Rams", pref: "nfl-lar" },
    { id: 15, name: "Miami Dolphins", pref: "nfl-mia" },
    { id: 16, name: "Minnesota Vikings", pref: "nfl-min" },
    { id: 17, name: "New England Patriots", pref: "nfl-ne" },
    { id: 18, name: "New Orleans Saints", pref: "nfl-no" },
    { id: 19, name: "New York Giants", pref: "nfl-nyg" },
    { id: 20, name: "New York Jets", pref: "nfl-nyj" },
    { id: 21, name: "Philadelphia Eagles", pref: "nfl-phi" },
    { id: 23, name: "Pittsburgh Steelers", pref: "nfl-pit" },
    { id: 25, name: "San Francisco 49ers", pref: "nfl-sf" },
    { id: 26, name: "Seattle Seahawks", pref: "nfl-sea" },
    { id: 27, name: "Tampa Bay Buccaneers", pref: "nfl-tb" },
    { id: 10, name: "Tennessee Titans", pref: "nfl-ten" },
    { id: 28, name: "Washington", pref: "nfl-wsh" }
  ],
};